---
name: "ThePornDB"
guid: "b88714eb-55e9-402f-ba72-4dfaa4b1401f"
version: "1.6.0.0"
targetAbi: "10.10.0.0"
framework: "net8.0"
owner: "theporndb"
overview: "Metadata for your porn collection"
description: >
  This metadata provider helps fill Jellyfin/Emby with information for your adult videos by pulling from ThePornDB.
category: "Metadata"
artifacts:
- "ThePornDB.dll"
changelog: >
  Jellyfin 10.10 compatibility update; dependency and ABI bump.
